gamekey/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("gamekey/", include("gamekeyservice.urls")),
    path('__debug__/', include('debug_toolbar.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gamekeyservice/urls.py
from django.urls import path
from .views import (
    HomeView,
    NewGame,
    Discounts,
    ComingSoon,
    GamePage,
    SearchView,
    GameListView,
    ShopCart,
    Profile,
    OrderedGamesInfo
)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", HomeView.as_view(), name="index"),
    path("new-games/", NewGame.as_view(), name="new_games"),
    path("discounts/", Discounts.as_view(), name="discounts"),
    path("coming-soon/", ComingSoon.as_view(), name="coming_soon"),
    path('search/', SearchView.as_view(), name='search'),
    path("game-page/<int:pk>/", GamePage.as_view(), name="game_page"),
    path("game-list/", GameListView.as_view(), name="game_list"),
    path("shop-cart/", ShopCart.as_view(), name="shop_cart"),
    path("profile/", Profile.as_view(), name="profile"),
    path("keysStorage/", OrderedGamesInfo.as_view(), name="order_games"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name = "game_keys"

templates/coming_soon.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Gamekey</title>
    {% load static %} {% load discount_counter %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <div class="mask">
      <img src="{% static '/Images/loader.gif' %}" alt="" />
    </div>
    <!--Начало панели навигации-->
    <nav class="nav">
      <div class="nav-content">
        <div class="logo">
          <p><a href="{% url 'game_keys:index' %}">GAMEKEY</a></p>
        </div>
        <div class="nav-list">
          <ul>
            <li class="new">
              <a href="{% url 'game_keys:new_games' %}">Новинки</a>
            </li>
            <li class="discount">
              <a href="{% url 'game_keys:discounts' %}">Знижки</a>
            </li>
            <li class="waiting">
              <a style="color: #ff55da" href="{% url 'game_keys:coming_soon' %}">Очікуванні</a>
            </li>
          </ul>
        </div>
        <form id="search-form" action="{% url 'game_keys:game_list' %}" method="get">
          <div class="input">
            <input autocomplete="off" type="text" placeholder="Знайти гру..." id="mySearch" name="q" />
            <button type="submit" id="search">
              <img src="{% static '/Images/Search.svg' %}" alt="Search Button" id="input_img" />
            </button>
          </div>
          <div class="search-request"></div>
        </form>
        <div class="logo-profile">
          <a href="{% url 'game_keys:profile' %}">
            <svg
              width="60"
              height="60"
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="1.2"
              viewBox="0 0 21 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Z"></path>
              <path d="M12 13a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"></path>
              <path d="M6.168 18.849A4 4 0 0 1 10 16h4a4 4 0 0 1 3.834 2.855"></path>
            </svg>
          </a>
        </div>
        <div class="logo-cart">
          <a href="{% url 'game_keys:shop_cart' %}">
            <p id="game_quantity">{% if shop_cart %}{{ shop_cart }}{% else %}0{% endif %}</p>
          </a>
        </div>
      </div>
    </nav>
    <!--Конец панели навигации-->
    <main>
      {% if coming_soon %}
      <div id="gameList">
        <div class="games-row">
          {% for game in coming_soon %}
          <div class="games">
            <div class="info">
              <a href="{% url 'game_keys:game_page' pk=game.id %}">
                <img src="{{ MEDIA_URL }}{{ game.image }}" alt="" />
              </a>
              <p class="game-name">{{ game.name }}</p>
              {% if game.discount %}
              <p class="discount-percent">-{{ game.discount }}%</p>
              {% endif %}
              <p
                class="price price-coing-soon"
                text="{{ game.price|discount:game.discount }}₴"
                id="game-id-{{ game.id }}"
              ></p>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      {% endif %}
    </main>
    <!--Начало футуера-->
    <footer>
      <div class="container">
        <div class="info-footer">
          <nav>
            <h2>Навігація</h2>
            <ul>
              <li><a href="{% url 'game_keys:new_games' %}">Новинки</a></li>
              <li><a href="{% url 'game_keys:discounts' %}">Знижки</a></li>
              <li>
                <a href="{% url 'game_keys:coming_soon' %}">Очікуванні</a>
              </li>
            </ul>
          </nav>

          <div class="team">
            <h2>Круті хлопці</h2>
            <ul>
              <li>Жовтоватюк Артем</li>
              <li>Журавльов Нікіта</li>
              <li>Приходько Олександр</li>
              <li>Кордунер Кевін</li>
              <li>Федорчук Дмитро</li>
              <li>Бокучава Олександр</li>
            </ul>
          </div>
          <div class="links-footer">
            <h2>Корисні посилання</h2>
            <ul>
              <li>
                <a href="https://github.com/RofLANi4/Gamekey-Project" target="_blank">GitHub</a>
              </li>
              <li>
                <a
                  href="https://drive.google.com/drive/folders/1yVpAAh5TZGNJV9cSZcerqVP6zl9KvYjG"
                  target="_blank"
                >
                  DB Files
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="policy">
          <p>&copy; GAMEKEY</p>
          <p>University project</p>
        </div>
      </div>
    </footer>
    <!--Конец футуера-->
    <script src="{% static 'js/content.js ' %}"></script>
    <script src="{% static 'js/loader.js' %}"></script>
    <script src="{% static 'js/addToCart.js' %}"></script>
  </body>
</html>

templates/discount.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Gamekey</title>
    {% load static %} {% load discount_counter %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <div class="mask">
      <img src="{% static '/Images/loader.gif' %}" alt="" />
    </div>
    <!--Начало панели навигации-->
    <nav class="nav">
      <div class="nav-content">
        <div class="logo">
          <p><a href="{% url 'game_keys:index' %}">GAMEKEY</a></p>
        </div>
        <div class="nav-list">
          <ul>
            <li class="new">
              <a href="{% url 'game_keys:new_games' %}">Новинки</a>
            </li>
            <li class="discount">
              <a style="color: #ff9900" href="{% url 'game_keys:discounts' %}">Знижки</a>
            </li>
            <li class="waiting">
              <a href="{% url 'game_keys:coming_soon' %}">Очікуванні</a>
            </li>
          </ul>
        </div>
        <form id="search-form" action="{% url 'game_keys:game_list' %}" method="get">
          <div class="input">
            <input autocomplete="off" type="text" placeholder="Знайти гру..." id="mySearch" name="q" />
            <button type="submit" id="search">
              <img src="{% static '/Images/Search.svg' %}" alt="Search Button" id="input_img" />
            </button>
          </div>
          <div class="search-request"></div>
        </form>
        <div class="logo-profile">
          <a href="{% url 'game_keys:profile' %}">
            <svg
              width="60"
              height="60"
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="1.2"
              viewBox="0 0 21 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Z"></path>
              <path d="M12 13a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"></path>
              <path d="M6.168 18.849A4 4 0 0 1 10 16h4a4 4 0 0 1 3.834 2.855"></path>
            </svg>
          </a>
        </div>
        <div class="logo-cart">
          <a href="{% url 'game_keys:shop_cart' %}">
            <p id="game_quantity">{% if shop_cart %}{{ shop_cart }}{% else %}0{% endif %}</p>
          </a>
        </div>
      </div>
    </nav>
    <!--Конец панели навигации-->

    <!-- Начало контента -->
    <main>
      {% if discount_games %}
      <div id="gameList">
        <div class="games-row">
          {% for game in discount_games %}
          <div class="games">
            <div class="info">
              <a href="{% url 'game_keys:game_page' pk=game.id %}">
                <img src="{{ MEDIA_URL }}{{ game.image }}" alt="" />
              </a>

              <p class="game-name">{{ game.name }}</p>
              {% if game.discount %}
              <p class="discount-percent">-{{ game.discount }}%</p>
              {% endif %}
              <p class="price" text="{{ game.price|discount:game.discount }}₴" id="game-id-{{ game.id }}"></p>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      {% endif %}
    </main>
    <!-- Конец контента -->

    <!--Начало футуера-->
    <footer>
      <div class="container">
        <div class="info-footer">
          <nav>
            <h2>Навігація</h2>
            <ul>
              <li><a href="{% url 'game_keys:new_games' %}">Новинки</a></li>
              <li><a href="{% url 'game_keys:discounts' %}">Знижки</a></li>
              <li>
                <a href="{% url 'game_keys:coming_soon' %}">Очікуванні</a>
              </li>
            </ul>
          </nav>

          <div class="team">
            <h2>Круті хлопці</h2>
            <ul>
              <li>Жовтоватюк Артем</li>
              <li>Журавльов Нікіта</li>
              <li>Приходько Олександр</li>
              <li>Кордунер Кевін</li>
              <li>Федорчук Дмитро</li>
              <li>Бокучава Олександр</li>
            </ul>
          </div>
          <div class="links-footer">
            <h2>Корисні посилання</h2>
            <ul>
              <li>
                <a href="https://github.com/RofLANi4/Gamekey-Project" target="_blank">GitHub</a>
              </li>
              <li>
                <a
                  href="https://drive.google.com/drive/folders/1yVpAAh5TZGNJV9cSZcerqVP6zl9KvYjG"
                  target="_blank"
                >
                  DB Files
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="policy">
          <p>&copy; GAMEKEY</p>
          <p>University project</p>
        </div>
      </div>
    </footer>
    <!--Конец футуера-->
    <script src="{% static 'js/content.js ' %}"></script>
    <script src="{% static 'js/loader.js' %}"></script>
    <script src="{% static 'js/addToCart.js' %}"></script>
  </body>
</html>

templates/game_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Gamekey</title>
    {% load static %} {% load discount_counter %} {% load genres_display %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <div class="mask">
      <img src="{% static '/Images/loader.gif' %}" alt="" />
    </div>
    <!--Начало панели навигации-->
    <nav class="nav">
      <div class="nav-content">
        <div class="logo">
          <p><a href="{% url 'game_keys:index' %}">GAMEKEY</a></p>
        </div>
        <div class="nav-list">
          <ul>
            <li class="new">
              <a href="{% url 'game_keys:new_games' %}">Новинки</a>
            </li>
            <li class="discount">
              <a href="{% url 'game_keys:discounts' %}">Знижки</a>
            </li>
            <li class="waiting">
              <a href="{% url 'game_keys:coming_soon' %}">Очікуванні</a>
            </li>
          </ul>
        </div>
        <form id="search-form" action="{% url 'game_keys:game_list' %}" method="get">
          <div class="input">
            <input autocomplete="off" type="text" placeholder="Знайти гру..." id="mySearch" name="q" />
            <button type="submit" id="search">
              <img src="{% static '/Images/Search.svg' %}" alt="Search Button" id="input_img" />
            </button>
          </div>
          <div class="search-request">
            <div class="hover"><p></p></div>
          </div>
        </form>
        <div class="logo-profile">
          <a href="{% url 'game_keys:profile' %}">
            <svg
              width="60"
              height="60"
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="1.2"
              viewBox="0 0 21 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Z"></path>
              <path d="M12 13a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"></path>
              <path d="M6.168 18.849A4 4 0 0 1 10 16h4a4 4 0 0 1 3.834 2.855"></path>
            </svg>
          </a>
        </div>
        <div class="logo-cart">
          <a href="{% url 'game_keys:shop_cart' %}">
            <p id="game_quantity">{% if shop_cart %}{{ shop_cart }}{% else %}0{% endif %}</p>
          </a>
        </div>
      </div>
    </nav>
    <!--Конец панели навигации-->

    <!--Начало страници игры-->
    <main>
      <div id="gamePage">
        <div class="game-describe">
          <div class="game-describe-top">
            <!-- <div class="orange-square"></div> -->
            <div class="game-photo">
              <img src="{{ MEDIA_URL }}{{ object.image }}" alt="" />
            </div>
            <div class="game-page-info">
              <p class="game-page-name">{{ object.name }}</p>
              <div class="game-price-cart">
                <p class="price" text="До кошика" id="game-id-{{ object.id }}"></p>
                <p class="game-price">{{ object.price|discount:game.discount }}₴</p>
              </div>
              <div class="game-type">
                <p class="left">Жанри</p>
                <p class="right">{% genres object.genre.all %}</p>
              </div>
              <div class="game-type">
                <p class="left">Дата виходу</p>
                <p class="right data">{{ release_date }}</p>
              </div>
              <div class="game-type">
                <p class="left">Розробник</p>
                <p class="right">{{ object.developer }}</p>
              </div>
              <div class="game-type">
                <p class="left">Платформа</p>
                <p class="right">PC</p>
              </div>
            </div>
          </div>

          <div class="game-describe-bottom">
            <div class="description">
              <p class="about">Про цю гру</p>
              <p class="definition">{{ object.description }}</p>
            </div>
          </div>
          <div class="recommendation">
            <p>Магазин рекомендує</p>
            <div class="recommendation-games">
              {% for game in recommend_games %}
              <div class="games">
                <div class="info">
                  <a href="{% url 'game_keys:game_page' pk=game.id %}">
                    <img src="{{ MEDIA_URL }}{{ game.image }}" alt="" />
                  </a>
                  <p class="game-name">{{ game.name }}</p>
                  {% if game.discount %}
                  <p class="discount-percent">-{{ game.discount }}%</p>
                  {% endif %}
                  <p
                    class="price"
                    text="{{ game.price|discount:game.discount }}₴"
                    id="game-id-{{ game.id }}"
                  ></p>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </main>

    <!--Конец страници игры -->

    <!--Начало футуера-->
    <footer>
      <div class="container">
        <div class="info-footer">
          <nav>
            <h2>Навігація</h2>
            <ul>
              <li><a href="{% url 'game_keys:new_games' %}">Новинки</a></li>
              <li><a href="{% url 'game_keys:discounts' %}">Знижки</a></li>
              <li>
                <a href="{% url 'game_keys:coming_soon' %}">Очікуванні</a>
              </li>
            </ul>
          </nav>

          <div class="team">
            <h2>Круті хлопці</h2>
            <ul>
              <li>Жовтоватюк Артем</li>
              <li>Журавльов Нікіта</li>
              <li>Приходько Олександр</li>
              <li>
                <a
                  href="https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjmh8nwv-v-AhWrDRAIHZuDAiQQwqsBegQICRAF&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DdQw4w9WgXcQ&usg=AOvVaw0aHtehaphMhOCAkCydRLZU"
                  style="color: fff"
                >
                  Кордунер Кевін
                </a>
              </li>
              <li>Федорчук Дмитро</li>
              <li>Бокучава Олександр</li>
            </ul>
          </div>
          <div class="links-footer">
            <h2>Корисні посилання</h2>
            <ul>
              <li>
                <a href="https://github.com/RofLANi4/Gamekey-Project" target="_blank">GitHub</a>
              </li>
              <li>
                <a
                  href="https://drive.google.com/drive/folders/1yVpAAh5TZGNJV9cSZcerqVP6zl9KvYjG"
                  target="_blank"
                >
                  DB Files
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="policy">
          <p>&copy; GAMEKEY</p>
          <p>University project</p>
        </div>
      </div>
    </footer>
    <!--Конец футуера-->
  </body>
  <script src="{% static 'js/content.js ' %}"></script>
  <script src="{% static 'js/loader.js' %}"></script>
  <script src="{% static 'js/addToCart.js' %}"></script>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Gamekey</title>
    {% load static %} {% load discount_counter %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <div class="mask">
      <img src="{% static '/Images/loader.gif' %}" alt="" />
    </div>
    <!--Начало панели навигации-->
    <nav class="nav">
      <div class="nav-content">
        <div class="logo">
          <p><a href="{% url 'game_keys:index' %}">GAMEKEY</a></p>
        </div>
        <div class="nav-list">
          <ul>
            <li class="new">
              <a href="{% url 'game_keys:new_games' %}">Новинки</a>
            </li>
            <li class="discount">
              <a href="{% url 'game_keys:discounts' %}">Знижки</a>
            </li>
            <li class="waiting">
              <a href="{% url 'game_keys:coming_soon' %}">Очікуванні</a>
            </li>
          </ul>
        </div>
        <form id="search-form" action="{% url 'game_keys:game_list' %}" method="get">
          <div class="input">
            <input autocomplete="off" type="text" placeholder="Знайти гру..." id="mySearch" name="q" />
            <button type="submit" id="search">
              <img src="{% static '/Images/Search.svg' %}" alt="Search Button" id="input_img" />
            </button>
          </div>
          <div class="search-request">
            <div class="hover"><p></p></div>
          </div>
        </form>
        <div class="logo-profile">
          <a href="{% url 'game_keys:profile' %}">
            <svg
              width="60"
              height="60"
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="1.2"
              viewBox="0 0 21 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Z"></path>
              <path d="M12 13a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"></path>
              <path d="M6.168 18.849A4 4 0 0 1 10 16h4a4 4 0 0 1 3.834 2.855"></path>
            </svg>
          </a>
        </div>
        <div class="logo-cart">
          <a href="{% url 'game_keys:shop_cart' %}">
            <p id="game_quantity">{% if shop_cart %}{{ shop_cart }}{% else %}0{% endif %}</p>
          </a>
        </div>
      </div>
    </nav>
    <!--Конец панели навигации-->

    <!--Начало слайдера-->
    <div id="slide">
      <div>
        <button id="buttonPrev">
          <img src="../static/Images/Prev.svg" alt="" />
        </button>
      </div>
      <div class="slides">
        <div class="overflow">
          <div class="images">
            {% if random_games %} {% for game in random_games %} {% if forloop.counter0|divisibleby:3%}
            <div class="images-block">
              {% endif %}
              <div>
                <a href="{% url 'game_keys:game_page' pk=game.id %}">
                  <img src="{{ MEDIA_URL }}{{ game.image }}" alt="game image" />
                </a>
                <p
                  class="price"
                  text="{{ game.price|discount:game.discount }}₴"
                  id="game-id-{{ game.id }}"
                ></p>
              </div>
              {% if forloop.counter|divisibleby:3 or forloop.last %}
            </div>
            {% endif %} {% endfor %}{% else %}
            <h1 class="images-block">There are no games yet</h1>
            {% endif %}
          </div>
        </div>
      </div>
      <div>
        <button id="buttonNext">
          <img src="../static/Images/Next.svg" alt="" />
        </button>
      </div>
    </div>
    <!--Конец слайдера-->

    <!--Начало нижней панели с играми-->
    <main>
      {% if random1_games %}
      <div id="gameList">
        <div class="games-row">
          {% for game in random1_games %}
          <div class="games">
            <div class="info">
              <a href="{% url 'game_keys:game_page' pk=game.id %}">
                <img src="{{ MEDIA_URL }}{{ game.image }}" alt="" />
              </a>
              <p class="game-name">{{ game.name }}</p>
              {% if game.discount %}
              <p class="discount-percent">-{{ game.discount }}%</p>
              {% endif %}
              <p class="price" text="{{ game.price|discount:game.discount }}₴" id="game-id-{{ game.id }}"></p>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      {% endif %}
    </main>

    <!--Конец нижней панели с играми-->

    <!--Начало футуера-->
    <footer>
      <div class="container">
        <div class="info-footer">
          <nav>
            <h2>Навігація</h2>
            <ul>
              <li><a href="{% url 'game_keys:new_games' %}">Новинки</a></li>
              <li><a href="{% url 'game_keys:discounts' %}">Знижки</a></li>
              <li>
                <a href="{% url 'game_keys:coming_soon' %}">Очікуванні</a>
              </li>
            </ul>
          </nav>

          <div class="team">
            <h2>Круті хлопці</h2>
            <ul>
              <li>Жовтоватюк Артем</li>
              <li>Журавльов Нікіта</li>
              <li>Приходько Олександр</li>
              <li>
                <a
                  href="https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjmh8nwv-v-AhWrDRAIHZuDAiQQwqsBegQICRAF&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DdQw4w9WgXcQ&usg=AOvVaw0aHtehaphMhOCAkCydRLZU"
                  style="color: fff"
                >
                  Кордунер Кевін
                </a>
              </li>
              <li>Федорчук Дмитро</li>
              <li>Бокучава Олександр</li>
            </ul>
          </div>
          <div class="links-footer">
            <h2>Корисні посилання</h2>
            <ul>
              <li>
                <a href="https://github.com/RofLANi4/Gamekey-Project" target="_blank">GitHub</a>
              </li>
              <li>
                <a
                  href="https://drive.google.com/drive/folders/1yVpAAh5TZGNJV9cSZcerqVP6zl9KvYjG"
                  target="_blank"
                >
                  DB Files
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="policy">
          <p>&copy; GAMEKEY</p>
          <p>University project</p>
        </div>
      </div>
    </footer>
    <!--Конец футуера-->

    <script src="{% static 'js/content.js ' %}"></script>
    <script src="{% static 'js/loader.js' %}"></script>
    <script src="{% static 'js/slider.js' %}"></script>
    <script src="{% static 'js/addToCart.js' %}"></script>
  </body>
</html>

templates/new-game.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>Document</title>
  </head>
  <body>
    <div class="mask">
      <img src="../static/Images/loader.gif" alt="" />
    </div>
    <!--Начало панели навигации-->
    <nav class="nav">
      <div class="nav-content">
        <div class="logo">
          <p><a href>GAMEKEY</a></p>
        </div>
        <div class="nav-list">
          <ul>
            <li class="new"><a href="new-game.html">Новинки</a></li>
            <li class="discount"><a href>Знижки</a></li>
            <li class="waiting"><a href>Очікуванні</a></li>
          </ul>
        </div>
        <div class="input">
          <input type="text" placeholder="Знайти гру..." id="mySearch" />
          <div class="search">
            <div>
              <img src="../static/Images/Search.svg" alt="Search Button" />
            </div>
          </div>
        </div>
        <div class="logo-basket">
          <img src="../static/Images/Basket.svg" alt="Basket Button" />
        </div>
      </div>
    </nav>
    <!--Конец панели навигации-->
  </body>
</html>